#ifdef PLATFORM_CONFIG_H
#define PLATFORM_CONFIG_H


#define CC2430_MEMCTR_FMAP_MASK  		0xCF
#define CC2430_MEMCTR_FMAP_OFFSET	4


#define RADIO_SEND_QUEUE_SIZE    500
#define RADIO_RECEIVE_QUEUE_SIZE    200

#define MCU_SLEEP_LOCK

#endif

