

#ifndef __SLEEPALARMCONSTANTS_H
#define __SLEEPALARMCONSTANTS_H

#define UQ_VIRTUALIZED_SLEEPALARM_MILLI_32  "VirtualizedAlarmMilli32P"
#define UQ_VIRTUALIZED_SLEEPALARM_32KHZ_32 "VirtualizedAlarm32Khz32P"

#endif
