COMPONENT=EMSnifferApp

######################


PFLAGS += -DADBG_LEVEL=9

PFLAGS += -DUSE_BOARD_LED

#使用串口调试模块
PFLAGS += -DUART_DEBUG

#射频，不限制地址
PFLAGS += -DNO_RADIO_ADDRESS_REQ

NID = 99

######################

include $(MAKERULES)

