.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH IPCRM 8 "13 June 2003" "Cygwin" "Linux Programmer's Manual"
.SH NAME
ipcrm \- remove ipc resources
.SH SYNOPSIS
.BI "ipcrm [ shm | msg | sem ] " id ...
.SH DESCRIPTION
.B ipcrm
will remove the resource(s) specified by
.IR id .
.SH SEE ALSO
.BR ipcs (8)
