COMPONENT = EmRouterCoordAppC


#############################

#使用串口调试模块
PFLAGS += -DUART_DEBUG -DUSE_BOARD_LED

PFLAGS += -DPACKET_LINK


PFLAGS += -DADBG_LEVEL=2000
USE_CC2420_STACK = 1
#MCU_SLEEP = 1

#################################

include $(MAKERULES)

